### ISSUE TITLE
Any examples of configuration using self-hosted packages?

### ISSUE THREAD

**Issue by seandan7** [nuxt-community/fontawesome-module#23]
Are there any examples or suggestions for the nuxt.config setup if using self-hosted fontAwesome packages? I noticed that if purchasing a pro license and not renewing, the icons will no longer be available via .npmrc and the app will break. 

Is there any known solution for this?

**Comment by pimlie** [comment]
@seandan7 Maybe a webpack alias could work?

**Comment by seandan7** [comment]
@pimlie That worked swimmingly!

**Comment by vakrolme** [comment]
@seandan7, could you please share your config for how you did it?

**Comment by seandan7** [comment]
@vakrolme I don't work where I used this code anymore. I should have commented it here. 

 I _believe_ it was something like this:
nuxt.config.js
```
module.exports = {
    build: {
        extend (config) {
            config.resolve.alias['@fontawesome']= path.join(this.options.srcDir, 'fontawesome-local')
        }
    }
}
```
With all of your local downloaded files in that directory.

**Comment by vakrolme** [comment]
Thanks @seandan7. I used nuxt's own [alias property](https://nuxtjs.org/docs/configuration-glossary/configuration-alias) instead:
```
import { resolve } from 'path';
export default {
  ...
  alias: {
    '@fortawesome/free-regular-svg-icons': resolve(__dirname, 'assets/icons/fontawesome-local/free-regular-svg-icons'),
  },
  ...
}
```
It's also important not to confuse which type of distribution you should put there, it should be [js-packages](https://github.com/FortAwesome/Font-Awesome/tree/6.x/js-packages/%40fortawesome/free-solid-svg-icons), not [js](https://github.com/FortAwesome/Font-Awesome/tree/6.x/js), so the directory you point to must feature **index.js** and a separate file for each icon, rather than **all.js**. That's why nothing worked for me until I figured it out.
